name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: cypress-do-zero-a-nuvem
        run: npm install

      - name: Run Cypress tests
        working-directory: cypress-do-zero-a-nuvem
        run: npx cypress run
